config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  root 'tickets#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ticket.rb
class Ticket
  include Mongoid::Document
  include Mongoid::Timestamps
  field :day, type: String
  field :spring, type: String
  field :date, type: Date
  field :remaining, type: String
  field :logged_time, type: String
  field :status, type: String
  field :description_remaining, type: String
  field :branch_detail, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
    
    
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:day,:spring, :date, :remaining,:logged_time,:status, :description_remaining, :branch_detail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, class: 'form') do |form| %>
  <% if ticket.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :day, class: 'form-label' %>
    <%= form.text_field :day, class: 'form-control' %>
  </div>

    <div class="form-group">
    <%= form.label :spring, class: 'form-label' %>
    <%= form.text_field :spring, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date, class: 'form-label' %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :remaining, class: 'form-label' %>
    <%= form.text_field :remaining, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= form.label :logged_time, class: 'form-label' %>
    <%= form.text_field :logged_time, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status, class: 'form-label' %>
    <%= form.select :status, options_for_select(['On hold','
Initialized', 'Finished']), { include_blank: true }, class: 'form-select' %>

  </div>

  <div class="form-group">
    <%= form.label :description_remaining, class: 'form-label' %>
    <%= form.text_area :description_remaining, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :branch_detail, class: 'form-label' %>
    <%= form.text_area :branch_detail, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
    <tr>
			<td><%= ticket.day %></td>
      <td><%= ticket.spring %></td>
			<td><%= ticket.date %></td>
			<td>
      <span class="badge bg-primary">
      <%= ticket.remaining %>
      </span>
      </td>
      <td><span class="badge bg-primary">
      <%= ticket.logged_time %>
      </span></td>
      <td>
       <% if ticket.status == 'On hold' %>
        <span class="badge bg-danger">
          <%= ticket.status %>
        </span>
      <% elsif ticket.status == 'Initialized' %>
        <span class="badge bg-warning">
          <%= ticket.status %>
        </span>
      <% elsif ticket.status == 'Finished' %>
        <span class="badge bg-success">
          <%= ticket.status %>
        </span>
      <% else %>
        <span class="badge bg-warning">
          <%= ticket.status %>
        </span>
      <% end %>
			<td><%= ticket.description_remaining %></td>
      </td>
      
			<td><%= ticket.branch_detail %></td>
      <td><span class="badge bg-success">
      <%= link_to "Show this ticket", ticket %>
      </span>
      </td>
		</tr>

app/views/tickets/edit.html.erb
<style>
.button-link {
  display: inline-block;
  padding: 10px 20px;
  background-color: #1963AE ;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  border: none;
  text-decoration: none;
}

.button-link:hover {
  background-color: #45a049;
   text-decoration: none;
   color:white;
   
}

.button-link:active {
  background-color: #3e8e41;
   text-decoration: none;
   color:white;
}

</style>
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket ,class:'button-link'%> 
  <%= link_to "Back to tickets", tickets_path ,class:'button-link'%>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>
<style>
.button-link {
  display: inline-block;
  padding: 10px 20px;
  background-color: #1963AE ;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  border: none;
  text-decoration: none;
}

.button-link:hover {
  background-color: #45a049;
   text-decoration: none;
   color:white;
   
}

.button-link:active {
  background-color: #3e8e41;
   text-decoration: none;
   color:white;
}
.badge {
border-radius: 100px;
 }

	
.badge a {
  color: white !important;
  text-decoration: none;
 }

 .badge a:hover {
	color:yellow !important;
 }
    

</style>

<h1>Tickets Tambora</h1><br>




<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Day</th>
      <th>Spring</th>
			<th>Date</th>
			<th>Remaining</th>
      <th>Logged time</th>
      <th>Status</th>
			<th>Description remaining</th>
			<th>Branch detail</th>
      <th>Action</th>
		</tr>
	</thead>
	<tbody>
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
  <% end %>
		
	
	</tbody>
	<tfoot>
		<tr>
			<th>Day</th>
      <th>Spring</th>
			<th>Date</th>
			<th>Remaining</th>
      <th>Logged time</th>
      <th>Status</th>
			<th>Description remaining</th>
			<th>Branch detail</th>
      <th>Action</th>
		</tr>
	</tfoot>
</table>

<br>
<%= link_to "New ticket", new_ticket_path, class: "button-link" %>
<a href="javascript:void(0);" class="button-link" onclick="location.reload();">Filter advance</a>

app/views/tickets/new.html.erb
<style>
.button-link {
  display: inline-block;
  padding: 10px 20px;
  background-color: #1963AE ;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  border: none;
  text-decoration: none;
}

.button-link:hover {
  background-color: #45a049;
   text-decoration: none;
   color:white;
   
}

.button-link:active {
  background-color: #3e8e41;
   text-decoration: none;
   color:white;
}

	
.badge a {
  color: white !important;
  text-decoration: none;
 }

 .badge a:hover {
	color:yellow !important;
 }
    

</style>
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Back to tickets", tickets_path,class: "button-link" %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>
<style>
.button-link {
  display: inline-block;
  padding: 10px 20px;
  background-color: #1963AE ;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  border: none;
  text-decoration: none;
}

.button-link:hover {
  background-color: #45a049;
   text-decoration: none;
   color:white;
   
}

.button-link:active {
  background-color: #3e8e41;
   text-decoration: none;
   color:white;
}


.button-delete {
  display: inline-block;
  padding: 10px 20px;
  background-color: red ;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  border: none;
  text-decoration: none;
}

.button-delete:hover {
  background-color: #45a049;
   text-decoration: none;
   color:white;
   
}

.button-delete:active {
  background-color: #3e8e41;
   text-decoration: none;
   color:white;
}
.badge a {
  color: white !important;
  text-decoration: none;
 }

 .badge a:hover {
	color:yellow !important;
 }

</style>
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Day</th>
      <th>Spring</th>
			<th>Date</th>
			<th>Remaining</th>
      <th>Logged time</th>
      <th>Status</th>
			<th>Description remaining</th>
			<th>Branch detail</th>
      <th>Action</th>
		</tr>
	</thead>
  <tbody>
  <%= render @ticket %>
	</tbody>
	<tfoot>
		<tr>
			<th>Day</th>
      <th>Spring</th>
			<th>Date</th>
			<th>Remaining</th>
      <th>Logged time</th>
      <th>Status</th>
			<th>Description remaining</th>
			<th>Branch detail</th>
      <th>Action</th>
		</tr>
	</tfoot>
</table>



<br>
<br>

<div>
  <%= link_to "Edit this ticket", edit_ticket_path(@ticket),class:'button-link' %> 
  <%= link_to "Back to tickets", tickets_path ,class:'button-link' %><br><br>
  <%= button_to "Delete this ticket", @ticket, method: :delete,class:'button-delete'%>
</div>